name: "SNMP Traps Receiver to MQTT"
description: "SNMP Traps Receiver to MQTT (Simple Network Management Protocol)"
url: "https://github.com/theprincelle/ha_addons/tree/main/snmp-trap-to-mqtt"
version: "1.0.13"
slug: "smmp-traps-receiver-to-mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_topic: "snmp"
  mqtt_user: ""
  mqtt_password: ""
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_user: str
  mqtt_password: str
image: "ghcr.io/theprincelle/ha-snmp-trap-to-mqtt-{arch}"
